//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCar
    {
        public int EntryId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int CarYear { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
