//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCar
    {
        public int CarId { get; set; }
        public string CustomerId { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public int CarYear { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
